# Generated by Django 2.0 on 2019-05-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Python',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=40)),
                ('video', models.IntegerField()),
                ('ppt', models.IntegerField()),
            ],
            options={
                'db_table': 'course_python',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=20)),
                ('note_nums', models.IntegerField()),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='Level_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.Level')),
            ],
            options={
                'db_table': 'level_list',
            },
        ),
        migrations.CreateModel(
            name='OnlineTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.CharField(max_length=100, null=True)),
                ('online_time', models.CharField(default=0, max_length=100, null=True)),
            ],
            options={
                'db_table': 'onlinetime',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('problem_text', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.Course_Python')),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_passwd', models.CharField(max_length=10)),
                ('user_progress', models.CharField(default=0, max_length=10)),
                ('focus', models.FloatField(default=0)),
                ('register_time', models.CharField(default=0, max_length=100)),
                ('current_time', models.CharField(default=0, max_length=100)),
                ('sum_time', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('online_days', models.IntegerField(default=0)),
                ('last_online_day', models.CharField(default=0, max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.User'),
        ),
        migrations.AddField(
            model_name='onlinetime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.User'),
        ),
    ]
