# Generated by Django 2.0 on 2019-05-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0002_problem_problem_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.User')),
            ],
            options={
                'db_table': 'user_problem',
            },
        ),
    ]
